version: '3.9'

services:
terraform:
  image: sstk-terraform-image:proj5
  build:
    context: .
    dockerfile: Dockerfile
  container_name: sstk-proj5
  volumes:
    - .:/iac
  command: tail -F anything
